.TH "Referencia del directorio C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia1_ej2" 3 "Guía 1 - Ejercicio 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia1_ej2
.SH SYNOPSIS
.br
.PP
.SS "Directorios"

.in +1c
.ti -1c
.RI "directorio \fBbuild\fP"
.br
.ti -1c
.RI "directorio \fBmain\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Este proyecto sirve como platilla para crear nuevos proyectos siguiendo el instructivo \fBProyecto Nuevo\fP\&. 
