.TH "C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia1_ej2/main/guia1_ej2.c" 3 "Guía 1 - Ejercicio 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia1_ej2/main/guia1_ej2.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include 'freertos/FreeRTOS\&.h'\fP
.br
\fR#include 'freertos/task\&.h'\fP
.br
\fR#include 'led\&.h'\fP
.br
\fR#include 'switch\&.h'\fP
.br

.SS "defines"

.in +1c
.ti -1c
.RI "#define \fBCONFIG_BLINK_PERIOD\fP   200"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBapp_main\fP (void)"
.br
.in -1c
.SH "Documentación de «define»"
.PP 
.SS "#define CONFIG_BLINK_PERIOD   200"

.PP
Definición en la línea \fB27\fP del archivo \fBguia1_ej2\&.c\fP\&.
.SH "Documentación de funciones"
.PP 
.SS "void app_main (void )"

.PP
Definición en la línea \fB33\fP del archivo \fBguia1_ej2\&.c\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Guía 1 - Ejercicio 2 del código fuente\&.
