.TH "C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia2_ej1/build/CMakeFiles/3.30.2/CompilerIdC/CMakeCCompilerId.c" 3 "Guía 2 - Ejercicio 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia2_ej1/build/CMakeFiles/3.30.2/CompilerIdC/CMakeCCompilerId.c
.SH SYNOPSIS
.br
.PP
.SS "defines"

.in +1c
.ti -1c
.RI "#define \fB__has_include\fP(x)"
.br
.ti -1c
.RI "#define \fBCOMPILER_ID\fP   ''"
.br
.ti -1c
.RI "#define \fBSTRINGIFY_HELPER\fP(X)"
.br
.ti -1c
.RI "#define \fBSTRINGIFY\fP(X)"
.br
.ti -1c
.RI "#define \fBPLATFORM_ID\fP"
.br
.ti -1c
.RI "#define \fBARCHITECTURE_ID\fP"
.br
.ti -1c
.RI "#define \fBDEC\fP(n)"
.br
.ti -1c
.RI "#define \fBHEX\fP(n)"
.br
.ti -1c
.RI "#define \fBC_STD_99\fP   199901L"
.br
.ti -1c
.RI "#define \fBC_STD_11\fP   201112L"
.br
.ti -1c
.RI "#define \fBC_STD_17\fP   201710L"
.br
.ti -1c
.RI "#define \fBC_STD_23\fP   202311L"
.br
.ti -1c
.RI "#define \fBC_VERSION\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char const  * \fBinfo_compiler\fP = 'INFO' ':' 'compiler[' COMPILER_ID ']'"
.br
.ti -1c
.RI "char const  * \fBinfo_platform\fP = 'INFO' ':' 'platform[' PLATFORM_ID ']'"
.br
.ti -1c
.RI "char const  * \fBinfo_arch\fP = 'INFO' ':' 'arch[' ARCHITECTURE_ID ']'"
.br
.ti -1c
.RI "const char * \fBinfo_language_standard_default\fP"
.br
.ti -1c
.RI "const char * \fBinfo_language_extensions_default\fP"
.br
.in -1c
.SH "Documentación de «define»"
.PP 
.SS "#define __has_include( x)"
\fBValor:\fP
.nf
0
.PP
.fi

.PP
Definición en la línea \fB17\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define ARCHITECTURE_ID"

.PP
Definición en la línea \fB745\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define C_STD_11   201112L"

.PP
Definición en la línea \fB831\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define C_STD_17   201710L"

.PP
Definición en la línea \fB832\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define C_STD_23   202311L"

.PP
Definición en la línea \fB833\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define C_STD_99   199901L"

.PP
Definición en la línea \fB830\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define C_VERSION"

.PP
Definición en la línea \fB843\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define COMPILER_ID   ''"

.PP
Definición en la línea \fB448\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define DEC( n)"
\fBValor:\fP
.nf
  ('0' + (((n) / 10000000)%10)), \\
  ('0' + (((n) / 1000000)%10)),  \\
  ('0' + (((n) / 100000)%10)),   \\
  ('0' + (((n) / 10000)%10)),    \\
  ('0' + (((n) / 1000)%10)),     \\
  ('0' + (((n) / 100)%10)),      \\
  ('0' + (((n) / 10)%10)),       \\
  ('0' +  ((n) % 10))
.PP
.fi

.PP
Definición en la línea \fB749\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define HEX( n)"
\fBValor:\fP
.nf
  ('0' + ((n)>>28 & 0xF)), \\
  ('0' + ((n)>>24 & 0xF)), \\
  ('0' + ((n)>>20 & 0xF)), \\
  ('0' + ((n)>>16 & 0xF)), \\
  ('0' + ((n)>>12 & 0xF)), \\
  ('0' + ((n)>>8  & 0xF)), \\
  ('0' + ((n)>>4  & 0xF)), \\
  ('0' + ((n)     & 0xF))
.PP
.fi

.PP
Definición en la línea \fB760\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define PLATFORM_ID"

.PP
Definición en la línea \fB579\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define STRINGIFY( X)"
\fBValor:\fP
.nf
STRINGIFY_HELPER(X)
.PP
.fi

.PP
Definición en la línea \fB469\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "#define STRINGIFY_HELPER( X)"
\fBValor:\fP
.nf
#X
.PP
.fi

.PP
Definición en la línea \fB468\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SH "Documentación de funciones"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definición en la línea \fB877\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SH "Documentación de variables"
.PP 
.SS "char const* info_arch = 'INFO' ':' 'arch[' ARCHITECTURE_ID ']'"

.PP
Definición en la línea \fB826\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "char const* info_compiler = 'INFO' ':' 'compiler[' COMPILER_ID ']'"

.PP
Definición en la línea \fB455\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "const char* info_language_extensions_default"
\fBValor inicial:\fP
.nf
= "INFO" ":" "extensions_default["





  "OFF"

"]"
.PP
.fi

.PP
Definición en la línea \fB859\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "const char* info_language_standard_default"
\fBValor inicial:\fP
.nf
=
  "INFO" ":" "standard_default[" C_VERSION "]"
.PP
.fi

.PP
Definición en la línea \fB856\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SS "char const* info_platform = 'INFO' ':' 'platform[' PLATFORM_ID ']'"

.PP
Definición en la línea \fB825\fP del archivo \fBCMakeCCompilerId\&.c\fP\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Guía 2 - Ejercicio 1 del código fuente\&.
