.TH "C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia2_ej1/build/esp-idf/mbedtls/mbedtls/library/error.c" 3 "Guía 2 - Ejercicio 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia2_ej1/build/esp-idf/mbedtls/mbedtls/library/error.c
.SH SYNOPSIS
.br
.PP
\fR#include 'common\&.h'\fP
.br
\fR#include 'mbedtls/error\&.h'\fP
.br

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Guía 2 - Ejercicio 1 del código fuente\&.
