.TH "C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia2_ej1/README.md" 3 "Guía 2 - Ejercicio 1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia2_ej1/README.md
.SH SYNOPSIS
.br
.PP
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Guía 2 - Ejercicio 1 del código fuente\&.
