.TH "Referencia del directorio C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia2_ej3" 3 "Guía 2 - Ejercicio 3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia2_ej3
.SH SYNOPSIS
.br
.PP
.SS "Directorios"

.in +1c
.ti -1c
.RI "directorio \fBbuild\fP"
.br
.ti -1c
.RI "directorio \fBmain\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Este ejemplo hace parpadear el LED 1 (verde 🟢), el LED 2 (amarillo 🟡) y el LED 3 (rojo 🔴) de la placa ESP-EDU, cada uno a un frecuencias fija diferente\&.

.PP
.SH "Cómo usar el ejemplo"
.PP

.PP
Seguir los pasos detallados en los siguientes instructivos (según sea necesario):

.PP
.IP "1." 4
\fBInstalación\fP
.IP "2." 4
\fBCompilación\fP
.IP "3." 4
\fBGrabación y Depuración\fP 
.PP

