.TH "C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia1_ej3/build/esp-idf/mbedtls/mbedtls/library/error.c" 3 "Guía 1 - Ejercicio 3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia1_ej3/build/esp-idf/mbedtls/mbedtls/library/error.c
.SH SYNOPSIS
.br
.PP
\fR#include 'common\&.h'\fP
.br
\fR#include 'mbedtls/error\&.h'\fP
.br

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Guía 1 - Ejercicio 3 del código fuente\&.
