.TH "C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia1_ej3/main/guia1_ej3.c" 3 "Guía 1 - Ejercicio 3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia1_ej3/main/guia1_ej3.c
.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br
\fR#include 'freertos/FreeRTOS\&.h'\fP
.br
\fR#include 'freertos/task\&.h'\fP
.br
\fR#include 'led\&.h'\fP
.br

.SS "Estructuras de datos"

.in +1c
.ti -1c
.RI "struct \fBleds\fP"
.br
.in -1c
.SS "defines"

.in +1c
.ti -1c
.RI "#define \fBCONFIG_BLINK_PERIOD\fP   100"
.br
.ti -1c
.RI "#define \fBON\fP   1"
.br
.ti -1c
.RI "#define \fBOFF\fP   2"
.br
.ti -1c
.RI "#define \fBTOGGLE\fP   3"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBdiagrama_de_flujo\fP (struct \fBleds\fP *puntero)"
.br
.ti -1c
.RI "void \fBapp_main\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "struct \fBleds\fP \fBmy_leds\fP"
.br
.in -1c
.SH "Documentación de «define»"
.PP 
.SS "#define CONFIG_BLINK_PERIOD   100"

.PP
Definición en la línea \fB29\fP del archivo \fBguia1_ej3\&.c\fP\&.
.SS "#define OFF   2"

.PP
Definición en la línea \fB31\fP del archivo \fBguia1_ej3\&.c\fP\&.
.SS "#define ON   1"

.PP
Definición en la línea \fB30\fP del archivo \fBguia1_ej3\&.c\fP\&.
.SS "#define TOGGLE   3"

.PP
Definición en la línea \fB32\fP del archivo \fBguia1_ej3\&.c\fP\&.
.SH "Documentación de funciones"
.PP 
.SS "void app_main (void )"

.PP
Definición en la línea \fB87\fP del archivo \fBguia1_ej3\&.c\fP\&.
.SS "void diagrama_de_flujo (struct \fBleds\fP * puntero)"

.PP
Definición en la línea \fB45\fP del archivo \fBguia1_ej3\&.c\fP\&.
.SH "Documentación de variables"
.PP 
.SS "struct \fBleds\fP my_leds"

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Guía 1 - Ejercicio 3 del código fuente\&.
