.TH "leds" 3 "Guía 1 - Ejercicio 3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leds
.SH SYNOPSIS
.br
.PP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "uint8_t \fBmode\fP"
.br
.ti -1c
.RI "uint8_t \fBn_led\fP"
.br
.ti -1c
.RI "uint8_t \fBn_ciclos\fP"
.br
.ti -1c
.RI "uint16_t \fBperiodo\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Definición en la línea \fB34\fP del archivo \fBguia1_ej3\&.c\fP\&.
.SH "Documentación de campos"
.PP 
.SS "uint8_t mode"

.PP
Definición en la línea \fB36\fP del archivo \fBguia1_ej3\&.c\fP\&.
.SS "uint8_t n_ciclos"

.PP
Definición en la línea \fB38\fP del archivo \fBguia1_ej3\&.c\fP\&.
.SS "uint8_t n_led"

.PP
Definición en la línea \fB37\fP del archivo \fBguia1_ej3\&.c\fP\&.
.SS "uint16_t periodo"

.PP
Definición en la línea \fB39\fP del archivo \fBguia1_ej3\&.c\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Guía 1 - Ejercicio 3 del código fuente\&.
