.TH "Referencia del directorio C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia1_ej4/build" 3 "Guía 1 - Ejercicio 4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia1_ej4/build
.SH SYNOPSIS
.br
.PP
.SS "Directorios"

.in +1c
.ti -1c
.RI "directorio \fBbootloader\fP"
.br
.ti -1c
.RI "directorio \fBCMakeFiles\fP"
.br
.ti -1c
.RI "directorio \fBconfig\fP"
.br
.ti -1c
.RI "directorio \fBesp\-idf\fP"
.br
.in -1c
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBproject_elf_src_esp32c6\&.c\fP"
.br
.in -1c
