.TH "Referencia del directorio C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia2_ej2/build/bootloader/CMakeFiles/3.30.2/CompilerIdC" 3 "Guía 2 - Ejercicio 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio C:/Repositorios/delaRosa_2C_2025/firmware/projects/guia2_ej2/build/bootloader/CMakeFiles/3.30.2/CompilerIdC
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBCMakeCCompilerId\&.c\fP"
.br
.in -1c
