.TH "Referencia del directorio C:/Repositorios/delaRosa_2C_2025/firmware/projects" 3 "Guía 1 - Ejercicio 5y6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio C:/Repositorios/delaRosa_2C_2025/firmware/projects
.SH SYNOPSIS
.br
.PP
.SS "Directorios"

.in +1c
.ti -1c
.RI "directorio \fBguia1_ej5\fP"
.br
.in -1c
