.TH "gpioConf_t" 3 "Guía 1 - Ejercicio 5y6" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gpioConf_t \- Estructura de configuración de un pin GPIO\&.  

.SH SYNOPSIS
.br
.PP
.SS "Campos de datos"

.in +1c
.ti -1c
.RI "gpio_t \fBpin\fP"
.br
.ti -1c
.RI "io_t \fBdir\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Estructura de configuración de un pin GPIO\&. 

Contiene el número de pin y la dirección de operación (entrada/salida)\&. 
.PP
Definición en la línea \fB45\fP del archivo \fBguia1_ej5y6\&.c\fP\&.
.SH "Documentación de campos"
.PP 
.SS "io_t dir"

.PP
Definición en la línea \fB48\fP del archivo \fBguia1_ej5y6\&.c\fP\&.
.SS "gpio_t pin"

.PP
Definición en la línea \fB47\fP del archivo \fBguia1_ej5y6\&.c\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Guía 1 - Ejercicio 5y6 del código fuente\&.
